import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "#f1f5f9" }}>
        {children}
      </body>
    </html>
  );
}

export const visbycf = localFont({
  src: [
    {
      path: "./Fonts/VisbyCF/VisbyLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./Fonts/VisbyCF/VisbyMedium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Fonts/VisbyCF/VisbyBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./Fonts/VisbyCF/VisbyExtrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./Fonts/VisbyCF/VisbyHeavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-visby",
});

export const din = localFont({
  src: [
    {
      path: "./Fonts/D-DIN/D-DIN.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Fonts/D-DIN/D-DINCondensed.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Fonts/D-DIN/D-DINExp.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-din",
});

export const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
  weight: ["400", "500"],
  preload: true,
  fallback: ["system-ui", "sans-serif"],
});
